const plantData = [
  {
    "id": "cylindrical-snake-plant",
    "common_name": "Cylindrical Snake Plant",
    "latin_name": "Sansevieria cv. 'Cylindrica'",
    "type": "Succulent",
    "soil": "Well\u2011draining cactus/succulent mix",
    "light": "Bright indirect to full sun",
    "water": "Allow soil to dry completely between waterings",
    "donts": "No soggy soil  \nNo heavy mixes  \nNo standing water",
    "image": "succulent.jpg"
  },
  {
    "id": "trailing-jade",
    "common_name": "Trailing Jade",
    "latin_name": "Peperomia rotundifolia",
    "type": "Succulent",
    "soil": "Loose peat\u2011based mix with perlite",
    "light": "Bright indirect light (tolerates lower light)",
    "water": "Water when top 1\u202fcm of soil is dry",
    "donts": "No soggy soil  \nNo standing water  \nNo harsh direct sun",
    "image": "succulent.jpg"
  },
  {
    "id": "pink-passion",
    "common_name": "Pink Passion",
    "latin_name": "Alocasia brancifolia 'Pink Passion'",
    "type": "Aroid",
    "soil": "Moisture\u2011retentive aroid mix (soil + bark + coco coir)",
    "light": "Bright indirect light",
    "water": "Keep evenly moist; water when top half of soil dries",
    "donts": "No direct sun  \nNo full drought  \nNo compact soil",
    "image": "aroid.jpg"
  },
  {
    "id": "african-mask",
    "common_name": "African Mask",
    "latin_name": "Alocasia \u00d7 amazonica 'Polly'",
    "type": "Aroid",
    "soil": "Chunky aroid mix (orchid bark + perlite + peat)",
    "light": "Bright indirect light",
    "water": "Allow top ~2\u202fcm soil to dry between waterings",
    "donts": "No waterlogged soil  \nNo harsh sun  \nNo standing water",
    "image": "aroid.jpg"
  },
  {
    "id": "calathea-makoyana",
    "common_name": "Calathea makoyana",
    "latin_name": "Calathea makoyana",
    "type": "Prayer Plant",
    "soil": "Rich organic potting mix (peat + perlite + bark), slightly acidic",
    "light": "Bright filtered/indirect light; medium to low tolerated",
    "water": "Keep soil damp but not soggy; water when top ~2\u20113\u202fcm dries",
    "donts": "No soggy soil  \nNo direct sun  \nNo low humidity",
    "image": "prayer_plant.jpg"
  },
  {
    "id": "polka-dot-begonia",
    "common_name": "Polka Dot Begonia",
    "latin_name": "Begonia maculata",
    "type": "Begonia",
    "soil": "Well\u2011draining, aerated potting mix (peat + perlite + bark)",
    "light": "Bright indirect light; morning sun OK",
    "water": "Water when top ~1\u202fcm dries; maintain moderate humidity (45\u201360%)",
    "donts": "No dry soil  \nNo overwatering  \nNo harsh direct sun",
    "image": "begonia.jpg"
  },
  {
    "id": "velvet-cardboard-anthurium",
    "common_name": "Velvet Cardboard Anthurium",
    "latin_name": "Anthurium clarinervium",
    "type": "Aroid",
    "soil": "Porous aroid mix (orchid bark + peat + perlite)",
    "light": "Bright filtered/indirect light",
    "water": "Water when top ~2\u202fcm dries; humidity \u226560%",
    "donts": "No direct sun  \nNo prolonged dryness  \nNo soggy mix",
    "image": "aroid.jpg"
  },
  {
    "id": "palm-begonia-indian-summer",
    "common_name": "Palm Begonia & Indian Summer",
    "latin_name": "Begonia luxurians & 'Indian Summer'",
    "type": "Begonia",
    "soil": "Rich loose mix (peat + compost + perlite)",
    "light": "Bright indirect light; dappled sun OK",
    "water": "Keep soil lightly moist; slight surface drying",
    "donts": "No waterlogging  \nNo low humidity  \nNo harsh direct sun",
    "image": "begonia.jpg"
  },
  {
    "id": "strelitzia-bird-of-paradise-all-50-pure",
    "common_name": "Strelitzia (Bird of Paradise) (All 50 Pure)",
    "latin_name": "Strelitzia nicolai",
    "type": "Palm",
    "soil": "Rich loamy mix with peat + perlite; well\u2011draining",
    "light": "Bright indirect light; tolerates some morning or dappled sun",
    "water": "Water when top ~5\u202fcm dries; keep soil evenly moist",
    "donts": "No standing water  \nNo harsh direct sun  \nNo low humidity",
    "image": "palm.jpg"
  },
  {
    "id": "ocean-bambino-spider-plant",
    "common_name": "Ocean Bambino Spider Plant",
    "latin_name": "Chlorophytum comosum 'Ocean Bambino'",
    "type": "Herbaceous",
    "soil": "Moist, loamy potting soil with good drainage",
    "light": "Bright indirect light; light shade",
    "water": "Keep soil lightly moist during growing season; reduce in winter",
    "donts": "No soggy soil  \nNo direct harsh sun  \nNo compact soil",
    "image": "herbaceous.jpg"
  },
  {
    "id": "tradescantia-nanouk",
    "common_name": "Tradescantia 'Nanouk'",
    "latin_name": "Tradescantia albiflora 'Nanouk'",
    "type": "Trailing",
    "soil": "Moist, well\u2011draining mix (potting + perlite)",
    "light": "Bright indirect light; up to 1\u20112\u202fh morning sun",
    "water": "Water when top ~2.5\u202fcm soil feels dry; avoid wetting leaves",
    "donts": "No soggy soil  \nNo water on leaves  \nNo low humidity",
    "image": "trailing.jpg"
  },
  {
    "id": "fittonia-verschaffeltii",
    "common_name": "Fittonia verschaffeltii",
    "latin_name": "Fittonia verschaffeltii",
    "type": "Herbaceous",
    "soil": "Peat\u2011based rich mix with perlite",
    "light": "Bright indirect light; medium",
    "water": "Keep soil moist but not waterlogged",
    "donts": "No soggy soil  \nNo direct sun  \nNo soil dryness",
    "image": "herbaceous.jpg"
  },
  {
    "id": "white-wave-philodendron",
    "common_name": "White Wave Philodendron",
    "latin_name": "Philodendron 'White Wave'",
    "type": "Aroid",
    "soil": "Well\u2011draining aroid mix (peat + perlite + bark)",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Keep soil consistently moist but not soggy; allow top ~2\u202fcm to dry between waterings",
    "donts": "No direct sun  \nNo waterlogged soil  \nNo low humidity",
    "image": "aroid.jpg"
  },
  {
    "id": "chinese-money-plant",
    "common_name": "Chinese Money Plant",
    "latin_name": "Pilea peperomioides",
    "type": "Herbaceous",
    "soil": "General potting mix with perlite for drainage",
    "light": "Bright indirect light; tolerates medium light",
    "water": "Water when top ~2.5\u202fcm dries; allow soil to dry between waterings",
    "donts": "No soggy soil  \nNo overwatering  \nNo low humidity",
    "image": "herbaceous.jpg"
  },
  {
    "id": "shamrock-oxalis-milkii",
    "common_name": "Shamrock (Oxalis milkii)",
    "latin_name": "Oxalis milkii",
    "type": "Bulb",
    "soil": "Light, well\u2011draining mix with sand or perlite",
    "light": "Bright indirect light; some direct morning sun okay",
    "water": "Keep soil evenly moist; water when top ~2.5\u20135\u202fcm dries; reduce during dormancy",
    "donts": "No soggy soil  \nNo prolonged dry periods  \nNo standing water",
    "image": "bulb.jpg"
  },
  {
    "id": "coleus-excellium-pinstripe-croton",
    "common_name": "Coleus \u2018Excellium\u2019 (Pin\u2011Stripe Croton)",
    "latin_name": "Coleus variegatum 'Excellium'",
    "type": "Coleus",
    "soil": "Rich, fertile, well\u2011draining loamy mix",
    "light": "Bright indirect light to partial sun; avoid harsh midday sun",
    "water": "Keep soil evenly moist; water when top ~2.5\u202fcm dries",
    "donts": "No soggy soil  \nNo extended drought  \nNo harsh direct sun",
    "image": "coleus.jpg"
  },
  {
    "id": "red-beauty-philodendron",
    "common_name": "Red Beauty Philodendron",
    "latin_name": "Philodendron 'Red Beauty'",
    "type": "Aroid",
    "soil": "Well\u2011draining aroid mix (peat + perlite + bark)",
    "light": "Bright indirect light; filtered light only",
    "water": "Allow top ~50% of soil to dry before watering; keep humidity moderate",
    "donts": "No sitting in wet soil  \nNo direct harsh sun  \nNo stagnant air",
    "image": "aroid.jpg"
  },
  {
    "id": "ocean-bambino-spider-plant",
    "common_name": "Ocean Bambino Spider Plant",
    "latin_name": "Chlorophytum comosum 'Ocean Bambino'",
    "type": "Herbaceous",
    "soil": "Loamy potting soil with good drainage",
    "light": "Bright indirect light; shaded from hot sun",
    "water": "Keep soil lightly moist in growing season; water sparingly in winter",
    "donts": "No soggy soil  \nNo direct sun  \nNo tap water with chlorine",
    "image": "herbaceous.jpg"
  },
  {
    "id": "tradescantia-nanouk",
    "common_name": "Tradescantia 'Nanouk'",
    "latin_name": "Tradescantia albiflora 'Nanouk'",
    "type": "Trailing",
    "soil": "Well\u2011draining mix (potting soil + perlite or coco coir)",
    "light": "Bright indirect light; up to 6\u20118\u202fh bright indirect",
    "water": "Water weekly or when top inch (~2.5\u202fcm) soil dries; keep slightly moist",
    "donts": "No soggy soil  \nNo watering foliage  \nNo low humidity",
    "image": "trailing.jpg"
  },
  {
    "id": "fittonia-verschaffeltii",
    "common_name": "Fittonia verschaffeltii",
    "latin_name": "Nerve Plant (Fittonia verschaffeltii)",
    "type": "Herbaceous",
    "soil": "Peat\u2011based slightly acidic mix with perlite",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Keep soil evenly moist; water when top ~1\u202fcm dries",
    "donts": "No soggy soil  \nNo direct sun  \nNo soil dryness",
    "image": "herbaceous.jpg"
  },
  {
    "id": "red-beauty-philodendron",
    "common_name": "Red Beauty Philodendron",
    "latin_name": "Philodendron 'Red Beauty'",
    "type": "Aroid",
    "soil": "Well\u2011draining aroid mix (peat + perlite + bark)",
    "light": "Bright indirect light; avoid harsh direct sun",
    "water": "Allow top half of soil to dry between waterings; keep humidity moderate",
    "donts": "No sitting in wet soil  \nNo harsh direct sun  \nNo stagnant air",
    "image": "aroid.jpg"
  },
  {
    "id": "ocean-bambino-spider-plant",
    "common_name": "Ocean Bambino Spider Plant",
    "latin_name": "Chlorophytum comosum 'Ocean Bambino'",
    "type": "Herbaceous",
    "soil": "Loamy potting soil with good drainage",
    "light": "Bright indirect light; shade from hot sun",
    "water": "Keep soil lightly moist during growing seasons; reduce watering in winter",
    "donts": "No soggy soil  \nNo direct harsh sun  \nNo chlorinated tap water",
    "image": "herbaceous.jpg"
  },
  {
    "id": "tradescantia-nanouk",
    "common_name": "Tradescantia 'Nanouk'",
    "latin_name": "Tradescantia albiflora 'Nanouk'",
    "type": "Trailing",
    "soil": "Moist, well\u2011draining mix (potting soil + perlite or coco coir)",
    "light": "Bright indirect light; can tolerate morning sun",
    "water": "Water when top ~2\u202fcm soil dries; avoid overwatering",
    "donts": "No soggy soil  \nNo wet foliage  \nNo low humidity",
    "image": "trailing.jpg"
  },
  {
    "id": "nerve-plant",
    "common_name": "Nerve Plant",
    "latin_name": "Firdonia verschaffeltii",
    "type": "Herbaceous",
    "soil": "Peat\u2011based mix with perlite",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Keep soil moist but not waterlogged",
    "donts": "No soggy soil  \nNo direct sun  \nNo soil dryness",
    "image": "herbaceous.jpg"
  },
  {
    "id": "prayer-plant-lemon-lime",
    "common_name": "Prayer Plant 'Lemon Lime'",
    "latin_name": "Maranta leuconeura 'Lemon Lime'",
    "type": "Prayer Plant",
    "soil": "Well\u2011draining peat\u2011based mix, slightly acidic",
    "light": "Bright indirect to medium light; avoid direct sun",
    "water": "Keep soil evenly moist; water when top ~1\u202fcm dries",
    "donts": "No soil dryness  \nNo direct sun  \nNo low humidity",
    "image": "prayer_plant.jpg"
  },
  {
    "id": "parlour-palm",
    "common_name": "Parlour Palm",
    "latin_name": "Chamaedorea elegans",
    "type": "Palm",
    "soil": "Rich, well\u2011draining loamy mix",
    "light": "Bright indirect light; tolerates medium light",
    "water": "Water when top ~2\u202fcm dries; keep soil evenly moist",
    "donts": "No standing water  \nNo harsh direct sun  \nNo low humidity",
    "image": "palm.jpg"
  },
  {
    "id": "swiss-cheese-plant",
    "common_name": "Swiss Cheese Plant",
    "latin_name": "Monstera deliciosa",
    "type": "Aroid",
    "soil": "Well\u2011draining peat-based or aroid mix with perlite",
    "light": "Bright indirect light; avoid full sun",
    "water": "Allow top ~5\u202fcm to dry before watering; keep slightly moist",
    "donts": "No overwatering  \nNo low light  \nNo soggy soil",
    "image": "aroid.jpg"
  },
  {
    "id": "dragon-tree",
    "common_name": "Dragon Tree",
    "latin_name": "Dracaena fragrans 'Golden Coast'",
    "type": "Dracaena",
    "soil": "Loose, loamy potting mix",
    "light": "Medium to bright indirect light; tolerates low light",
    "water": "Allow 50\u201375% of soil to dry between waterings",
    "donts": "No overwatering  \nNo soggy soil  \nNo harsh direct sun",
    "image": "dracaena.jpg"
  },
  {
    "id": "dwarf-fiddleleaf-fig",
    "common_name": "Dwarf Fiddle\u2011Leaf Fig",
    "latin_name": "Ficus lyrata",
    "type": "Fig",
    "soil": "Well\u2011draining peat\u2011based or loamy mix",
    "light": "Bright indirect light; avoid harsh direct sun",
    "water": "Water when top ~2.5\u202fcm (1\u202fin) soil is dry; typically every 1\u20132 weeks",
    "donts": "No overwatering  \nNo soggy soil  \nNo direct harsh sun",
    "image": "fig.jpg"
  },
  {
    "id": "monkey-mask",
    "common_name": "Monkey Mask",
    "latin_name": "Monstera adansonii",
    "type": "Aroid",
    "soil": "Moist, well\u2011draining peat\u2011based mix",
    "light": "Bright indirect light; limited morning direct sun okay",
    "water": "Water when top ~2\u20133\u202fcm soil dries; allow drying between waterings",
    "donts": "No soggy soil  \nNo harsh direct sun  \nNo stagnant water",
    "image": "aroid.jpg"
  },
  {
    "id": "marble-queen-pothos",
    "common_name": "Marble Queen Pothos",
    "latin_name": "Epipremnum pinnatum 'Marble Queen'",
    "type": "Pothos",
    "soil": "Well\u2011draining, rich potting mix (potting + perlite + bark)",
    "light": "Bright indirect light (medium to bright; avoid low light to preserve variegation)",
    "water": "Allow top ~50% of soil to dry between waterings (approx every 7\u201310 days)",
    "donts": "No overwatering  \nNo low light  \nNo standing water",
    "image": "pothos.jpg"
  },
  {
    "id": "golden-pothos-devils-ivy",
    "common_name": "Golden Pothos (Devil\u2019s Ivy)",
    "latin_name": "Epipremnum aureum 'Golden Pothos'",
    "type": "Pothos",
    "soil": "General potting mix with perlite",
    "light": "Bright indirect to low light (tolerates low), avoid direct sun",
    "water": "Water every 1\u20132 weeks; allow soil to dry between waterings",
    "donts": "No soggy soil  \nNo harsh direct sun  \nNo stagnant water",
    "image": "pothos.jpg"
  },
  {
    "id": "variegated-wax-plant",
    "common_name": "Variegated Wax Plant",
    "latin_name": "Hoya carnosa 'Tricolor'",
    "type": "Hoya",
    "soil": "Well\u2011draining mix (potting soil + perlite + orchid bark)",
    "light": "Bright indirect light; avoid full direct sun",
    "water": "Water every 1\u20132 weeks; allow soil to dry out between waterings",
    "donts": "No overwatering  \nNo full shade  \nNo soggy soil",
    "image": "hoya.jpg"
  },
  {
    "id": "pinstripe-calathea",
    "common_name": "Pin\u2011Stripe Calathea",
    "latin_name": "Calathea ornata",
    "type": "Prayer Plant",
    "soil": "Rich, moist but well\u2011draining peat\u2011based mix (peat + perlite + bark)",
    "light": "Bright filtered/indirect light; medium tolerated",
    "water": "Keep soil moist but not soggy; water when top ~2.5\u202fcm (1\u202fin) dries",
    "donts": "No soggy soil  \nNo direct sun  \nNo low humidity",
    "image": "prayer_plant.jpg"
  },
  {
    "id": "boston-fern",
    "common_name": "Boston Fern",
    "latin_name": "Nephrolepis exaltata",
    "type": "Fern",
    "soil": "Rich, organic, well\u2011draining but moisture\u2011holding mix (peat + perlite + compost)",
    "light": "Bright indirect light to light shade; avoid direct sun",
    "water": "Keep soil consistently moist but not waterlogged; allow top ~2\u202fcm to dry slightly between waterings; high humidity essential",
    "donts": "No soggy soil  \nNo direct sun  \nNo low humidity",
    "image": "fern.jpg"
  },
  {
    "id": "kentia-palm",
    "common_name": "Kentia Palm",
    "latin_name": "Kenthia Palm (Howea forsteriana)",
    "type": "Palm",
    "soil": "Well\u2011draining sandy or loamy mix",
    "light": "Bright indirect to moderate light; tolerates low light; avoid harsh sun",
    "water": "Water when top ~2\u202fcm (1\u202fin) soil is dry; allow soil to slightly dry between waterings; moderate humidity",
    "donts": "No standing water  \nNo harsh direct sun  \nNo overly dry air",
    "image": "palm.jpg"
  },
  {
    "id": "croton-mammi",
    "common_name": "Croton 'Mammi'",
    "latin_name": "Codiaeum variegatum 'Mammi'",
    "type": "Croton",
    "soil": "Rich, well\u2011draining potting mix",
    "light": "Bright indirect to partial direct sun (morning or filtered)",
    "water": "Keep soil lightly moist; water when top ~2\u202fcm dries",
    "donts": "No low humidity  \nNo direct harsh sun  \nNo soggy soil",
    "image": "croton.jpg"
  },
  {
    "id": "rubber-plant-robusta",
    "common_name": "Rubber Plant 'Robusta'",
    "latin_name": "Ficus elastica 'Robusta'",
    "type": "Fig",
    "soil": "Well\u2011draining mix (peat + perlite + pine bark)",
    "light": "Bright indirect light; tolerates moderate light",
    "water": "Water when top ~2.5\u202fcm dries; allow soil to partially dry",
    "donts": "No standing water  \nNo overwatering  \nNo direct harsh sun",
    "image": "fig.jpg"
  },
  {
    "id": "monkey-mask",
    "common_name": "Monkey Mask",
    "latin_name": "Monstera adansonii",
    "type": "Aroid",
    "soil": "Moist but well\u2011draining peat\u2011based aroid mix",
    "light": "Bright indirect light; limited morning sun OK",
    "water": "Water when top ~2\u202fcm dries; allow drying between waterings",
    "donts": "No soggy soil  \nNo harsh direct sun  \nNo stagnant water",
    "image": "aroid.jpg"
  },
  {
    "id": "princess-plant",
    "common_name": "Princess Plant",
    "latin_name": "Clusia rosea",
    "type": "Tree/Foliage",
    "soil": "Rich, loose organic potting mix",
    "light": "Bright indirect to moderate light",
    "water": "Keep evenly moist; water when surface begins to dry",
    "donts": "No soggy soil  \nNo waterlogging  \nNo full shade",
    "image": "tree_foliage.jpg"
  },
  {
    "id": "maidenhair-fern",
    "common_name": "Maidenhair Fern",
    "latin_name": "Adiantum raddianum",
    "type": "Fern",
    "soil": "Rich humus\u2011rich, well\u2011draining soil with organic matter",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Keep soil consistently moist but not waterlogged; water frequently to maintain even moisture",
    "donts": "No drying out  \nNo soggy soil  \nNo direct harsh sun",
    "image": "fern.jpg"
  },
  {
    "id": "cast-iron-plant",
    "common_name": "Cast Iron Plant",
    "latin_name": "Aspidistra elatior",
    "type": "Herbaceous",
    "soil": "Loamy, humus-rich potting mix",
    "light": "Low to medium indirect light; avoid direct sun",
    "water": "Allow soil to dry slightly between waterings; water when top ~2\u202fcm dries",
    "donts": "No overwatering  \nNo harsh direct sun  \nNo dry soil",
    "image": "herbaceous.jpg"
  },
  {
    "id": "asparagus-fern",
    "common_name": "Asparagus Fern",
    "latin_name": "Asparagus setaceus",
    "type": "Herbaceous",
    "soil": "Light, well\u2011draining mix (peat + perlite)",
    "light": "Bright indirect light to medium; tolerates partial shade",
    "water": "Water when top ~2\u202fcm soil dries; keep evenly moist",
    "donts": "No soggy soil  \nNo direct harsh sun  \nNo dry, dusty air",
    "image": "herbaceous.jpg"
  },
  {
    "id": "english-ivy",
    "common_name": "English Ivy",
    "latin_name": "Hedera helix \u2018Green\u2019",
    "type": "Vine",
    "soil": "Moist, well\u2011draining loamy mix",
    "light": "Bright indirect to medium light; avoid intense direct sun",
    "water": "Water when top ~2\u202fcm dries; allow slight drying between waterings",
    "donts": "No soggy soil  \nNo harsh direct sun  \nNo low light leading to legginess",
    "image": "vine.jpg"
  },
  {
    "id": "prayer-plant-lemon-lime",
    "common_name": "Prayer Plant 'Lemon Lime'",
    "latin_name": "Maranta leuconeura 'Lemon Lime'",
    "type": "Prayer Plant",
    "soil": "Well\u2011draining peat\u2011based mix with perlite and compost; slightly acidic",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Keep soil consistently moist but not waterlogged; water every 1\u20132 weeks, allowing soil to dry halfway down",
    "donts": "No soggy soil  \nNo direct sun  \nNo low humidity",
    "image": "prayer_plant.jpg"
  },
  {
    "id": "variegated-wax-plant-hoya-tricolor",
    "common_name": "Variegated Wax Plant (Hoya Tricolor)",
    "latin_name": "Hoya carnosa 'Tricolor'",
    "type": "Hoya",
    "soil": "Well\u2011draining mix (potting soil + perlite and optional orchid bark)",
    "light": "Medium to bright indirect light; no direct sun",
    "water": "Allow soil to dry between waterings; water every 1\u20132 weeks",
    "donts": "No overwatering  \nNo full direct sun  \nNo prolonged dry spells",
    "image": "hoya.jpg"
  },
  {
    "id": "echeveria-spp",
    "common_name": "Echeveria spp.",
    "latin_name": "Echeveria spp.",
    "type": "Succulent",
    "soil": "Very well\u2011draining gritty cactus/succulent mix",
    "light": "Full bright light with at least some direct morning sun",
    "water": "Allow soil to dry completely between waterings; soak\u2011and\u2011dry cycle",
    "donts": "No overwatering  \nNo low light  \nNo water in rosette",
    "image": "succulent.jpg"
  },
  {
    "id": "champion-pink-anthurium",
    "common_name": "Champion Pink Anthurium",
    "latin_name": "Anthurium andraeanum 'Champion Pink'",
    "type": "Aroid",
    "soil": "Coarse, chunky mix (orchid bark + peat + perlite)",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Water when 50\u201175% of soil is dry; keep humidity high",
    "donts": "No soggy soil  \nNo prolonged dryness  \nNo harsh direct sun",
    "image": "aroid.jpg"
  },
  {
    "id": "raindrop-peperomia",
    "common_name": "Raindrop Peperomia",
    "latin_name": "Peperomia polybotrya (Raindrop Peperomia)",
    "type": "Succulent",
    "soil": "Well\u2011draining potting soil + perlite or coco chips",
    "light": "Bright indirect light; warm humidity preferred",
    "water": "Water when top ~2\u202fcm dries; avoid over\u2011watering; allow partial drying",
    "donts": "No soggy soil  \nNo low humidity  \nNo prolonged overwatering",
    "image": "succulent.jpg"
  },
  {
    "id": "pepperspot-peperomia",
    "common_name": "Pepperspot Peperomia",
    "latin_name": "Peperomia pepperspot",
    "type": "Succulent",
    "soil": "Well\u2011draining mix (peat + perlite)",
    "light": "Bright indirect light; avoids direct sun",
    "water": "Water when top ~1\u202fcm dries; keep slightly moist",
    "donts": "No soggy soil  \nNo direct sun  \nNo stagnant water",
    "image": "succulent.jpg"
  },
  {
    "id": "champion-pink-anthurium",
    "common_name": "Champion Pink Anthurium",
    "latin_name": "Anthurium andraeanum 'Champion Pink'",
    "type": "Aroid",
    "soil": "Coarse chunky mix (orchid bark + peat + perlite)",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Water when 50\u201375% of soil is dry; maintain high humidity",
    "donts": "No soggy soil  \nNo prolonged dryness  \nNo harsh direct sun",
    "image": "aroid.jpg"
  },
  {
    "id": "echeveria-spp",
    "common_name": "Echeveria spp.",
    "latin_name": "Echeveria spp.",
    "type": "Succulent",
    "soil": "Extremely well\u2011draining gritty cactus/succulent mix (perlite/pumice/sand)",
    "light": "Full bright light with some direct morning or afternoon sun",
    "water": "Allow soil to dry completely between waterings; use soak\u2011and\u2011dry cycle",
    "donts": "No overwatering  \nNo low light (legginess)  \nNo water in rosette",
    "image": "succulent.jpg"
  },
  {
    "id": "raindrop-peperomia",
    "common_name": "Raindrop Peperomia",
    "latin_name": "Peperomia polybotrya (Raindrop)",
    "type": "Succulent",
    "soil": "Well\u2011draining mix (peat or coco + perlite/chips)",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Water when top ~2\u202fcm dries; avoid overwatering; allow partial drying",
    "donts": "No soggy soil  \nNo prolonged overwatering  \nNo low humidity",
    "image": "succulent.jpg"
  },
  {
    "id": "pepperspot-peperomia",
    "common_name": "Pepperspot Peperomia",
    "latin_name": "Peperomia pepperspot",
    "type": "Succulent",
    "soil": "Well\u2011draining mix (peat + perlite)",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Water when top ~1\u202fcm dries; keep soil slightly moist",
    "donts": "No soggy soil  \nNo direct sun  \nNo stagnant water",
    "image": "succulent.jpg"
  },
  {
    "id": "zebra-plant",
    "common_name": "Zebra Plant",
    "latin_name": "Alocasia zebrina",
    "type": "Aroid",
    "soil": "Rich, well\u2011draining mix (peat + perlite + coco coir + bark)",
    "light": "Bright indirect to dappled sunlight; avoid harsh midday sun",
    "water": "Keep soil evenly moist; allow top ~2\u202fcm to dry slightly before watering",
    "donts": "No soggy soil  \nNo low light  \nNo overly dry air",
    "image": "aroid.jpg"
  },
  {
    "id": "dwarf-fiddleleaf-fig",
    "common_name": "Dwarf Fiddle\u2011Leaf Fig",
    "latin_name": "Ficus lyrata",
    "type": "Fig",
    "soil": "Well\u2011draining peat\u2011based or loamy mix",
    "light": "Bright indirect light; can tolerate some direct morning sun but avoid harsh midday light",
    "water": "Water when top ~2.5\u202fcm soil is dry (every 1\u20132 weeks); keep humidity moderate",
    "donts": "No overwatering  \nNo soggy soil  \nNo sudden environment changes",
    "image": "fig.jpg"
  },
  {
    "id": "gymnocalycium-cactus",
    "common_name": "Gymnocalycium Cactus",
    "latin_name": "Gymnocalycium spp.",
    "type": "Cactus",
    "soil": "Gravelly sandy cactus mix",
    "light": "Full sun to bright indirect light",
    "water": "Water thoroughly when soil is completely dry; allow soaking and full dry cycle",
    "donts": "No overwatering  \nNo low light  \nNo soggy soil",
    "image": "cactus.jpg"
  },
  {
    "id": "pepperspot-peperomia",
    "common_name": "Pepperspot Peperomia",
    "latin_name": "Peperomia pepperspot",
    "type": "Succulent",
    "soil": "Well\u2011draining mix (peat + perlite)",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Water when top ~1\u202fcm dries; maintain slightly moist soil",
    "donts": "No soggy soil  \nNo direct sun  \nNo stagnant water",
    "image": "succulent.jpg"
  },
  {
    "id": "bunnyear-cactus",
    "common_name": "Bunny\u2011Ear Cactus",
    "latin_name": "Opuntia albispina",
    "type": "Cactus",
    "soil": "Very well\u2011draining sandy/gritty cactus mix (perlite/sand + cactus mix)",
    "light": "Full bright sun (6\u20138\u202fhr direct light)",
    "water": "Allow soil to dry completely between thorough waterings; water sparingly (even less in winter)",
    "donts": "No overwatering  \nNo low light  \nNo soggy soil",
    "image": "cactus.jpg"
  },
  {
    "id": "pink-anthurium",
    "common_name": "Pink Anthurium",
    "latin_name": "Anthurium andraeanum 'Champion Pink'",
    "type": "Aroid",
    "soil": "Light, coarse, well\u2011draining mix (orchid bark + peat + perlite)",
    "light": "Bright indirect light; avoid direct sun",
    "water": "Keep soil lightly moist; water when top ~2.5\u202fcm dries; maintain high humidity",
    "donts": "No soggy soil  \nNo prolonged dryness  \nNo harsh direct sun",
    "image": "aroid.jpg"
  }
];